server:
  port: 80
  servlet:
    session:
      timeout: 1m # session会话超时时间，默认情况 下是30分钟（m）,不能小于1分钟
      cookie:
        name: JSESSIONID # 指定浏览器Cookie中关于SessionID保存的那个名称

spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: Love1303
    url: jdbc:mysql://127.0.0.1:3306/dyb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver

mengxuegu:
  security:
    authentication:
      loginPage: /login/page
      loginProcessingUrl: /login/form
      usernameParameter: name
      passwordParameter: pwd
      staticPaths:
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT

